Add files via upload

diff --git a/SCRIPT ACKHTTP SERVER/SCRIPT ACKHTTP SERVER/FERRAMENTAS/tweaker b/SCRIPT ACKHTTP SERVER/SCRIPT ACKHTTP SERVER/FERRAMENTAS/tweaker
--- a/SCRIPT ACKHTTP SERVER/SCRIPT ACKHTTP SERVER/FERRAMENTAS/tweaker
+++ b/SCRIPT ACKHTTP SERVER/SCRIPT ACKHTTP SERVER/FERRAMENTAS/tweaker
@@ -5,7 +5,7 @@ echo -e "\E[41;1;37m  TWEAKER QUICK    \E[0m"
 if [[ `grep -c "^#PH56" /etc/sysctl.conf` -eq 1 ]]
 then
 echo -e "\033[01;34m===================================================================="
-	echo -e "\033[1;33mCONFIGURAÇÃO TWEAKER JA APLICADO !\033[1;37m"
+	echo -e "\033[1;33mOOPS! CONFIGURAÇÃO TWEAKER JA APLICADO...\033[1;37m"
 echo -e "\033[01;34m====================================================================\033[1;37m"
 	echo ""
 	read -p "DESEJA REMOVER CONFIGURAÇÃO TWEAKER? [sim/nao]: " -e -i nao resposta0
@@ -182,15 +182,30 @@ net.ipv6.conf.lo.disable_ipv6 = 1" /etc/sysctl.conf > /tmp/syscl && mv /tmp/sysc
 
 sysctl -p /etc/sysctl.conf > /dev/null
 echo -n > /etc/sysctl.conf
+crontab -u root -l | grep -v '@daily /sbin/fstrim -a || true'  | crontab -u root -
+crontab -u root -l | grep -v '@daily /bin/ackclear'  | crontab -u root -
+crontab -u root -l | grep -v '@daily sleep 10s && /bin/prissh'  | crontab -u root -
+crontab -u root -l | grep -v '@reboot sleep 10s && /sbin/iptables-restore < /etc/iptables.conf'  | crontab -u root -
 crontab -u root -l | grep -v '@reboot sleep 10s && /bin/tweaker'  | crontab -u root -
 crontab -u root -l | grep -v '@reboot sleep 10s && /bin/acksyshttpack'  | crontab -u root -
+crontab -u root -l | grep -v '@reboot sleep 10s && /bin/prissh'  | crontab -u root -
 cd /bin/ && rm -f acksyshttpack*
+cd /bin/ && rm -f ackclear*
+cd /bin/ && rm -f prissh*
 chattr -i /etc/resolv.conf
-sleep 2s
+echo -n > /etc/security/limits.conf
+echo -n > /etc/systemd/system.conf
+echo -n > /etc/systemd/logind.conf
+echo -n > /etc/systemd/resolved.conf
+echo -n > /etc/systemd/resolved.conf
+
+sleep 3s
 		echo ""
 	echo -e "\033[1;32mCONFIGURAÇÃO DE TWEAKER REMOVIDO COM SUCESSO !"
+sleep 3s
 echo ""
-	echo -e "\033[1;33mREINICIE SEU SERVIDOR !"
+	echo -e "\033[1;33mREINICIE SEU SERVIDOR..."
+sleep 3s
 		echo ""
 echo -e "\033[1;36mVOLTANDO AO MENU..."
 sleep 6s
@@ -203,15 +218,14 @@ menu
 	fi
 else
 echo -e "\033[01;34m===================================================================="
-echo -e "\033[1;33m                ATENÇÃO AOS DETALHES ABAIXO !"
+echo -e "\033[1;33mUTILIZE EM SISTEMA ATUALIZADOS \033[1;32m(UBUNTU OU DEBIAN )"
 echo -e "\033[01;34m===================================================================="
+echo ""
 echo -e "\033[1;33mSERA APLICADO AJUSTES NO SERVIDOR, PARA OBTER UMA ALTA PERFORMANCE"
-echo -e "\033[1;33mAUMENTANDO LIMITE DE VALORES PADRÕES DA PILHA KERNEL DO LINUX COMO; 
-\033[1;32m(SYSCTL) \033[1;37m+ \033[1;32m(CWND) \033[1;37m+ \033[1;32m(DNS) \033[1;37m+ \033[1;32m(TCP) \033[1;37m+ \033[1;32m(MTU) \033[1;37m+ \033[1;32m(TX & RX)\033[1;37m"
+echo -e "\033[1;33mAUMENTANDO LIMITE DE VALORES PADRÃO DO KERNEL LINUX"
 echo ""
 echo -e "\033[1;33mO RENDIMENTO PODE SER SUPERIOR OU NÃO."
-echo -e "\033[01;34m===================================================================="
-echo -e "\033[1;33mLEMBRANDO QUE NÃO IRA AUMENTAR SUA INTERNET MILAGROSAMENTE !"
+echo ""
 echo -e "\033[01;34m====================================================================\033[1;37m"
 echo ""
 	read -p "DESEJAR INSTALAR TWEAKER ? [sim/nao]: " -e -i sim resposta
@@ -219,13 +233,12 @@ echo ""
 	echo ""
 	echo " " >> /etc/sysctl.conf
 	echo "#PH56" >> /etc/sysctl.conf
-
 #"1"
 
 echo "fs.nr_open = 1048576
 fs.file-max = 1048576
 vm.vfs_cache_pressure = 200
-vm.swappiness = 1
+vm.swappiness = 100
 vm.page-cluster = 16
 vm.dirty_ratio = 1
 vm.dirty_background_ratio = 1
@@ -391,17 +404,29 @@ net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
 #
 cd /bin/ && rm -f tweaker*
 cd /bin/ && rm -f acksyshttpack*
-rm -f tweaker*
-rm -f acksyshttpack*
+cd /bin/ && rm -f ackclear*
+cd /bin/ && rm -f prissh*
 cd /bin/ && wget https://raw.githubusercontent.com/ACKHTTP/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/tweaker > /dev/null 2>&1
 cd /bin/ && wget https://raw.githubusercontent.com/ACKHTTP/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/acksyshttpack > /dev/null 2>&1
+cd /bin/ && wget https://raw.githubusercontent.com/ACKHTTP/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/ackclear > /dev/null 2>&1
+cd /bin/ && wget https://raw.githubusercontent.com/ACKHTTP/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/prissh > /dev/null 2>&1
 cd /bin/ && chmod +x tweaker
 cd /bin/ && chmod +x acksyshttpack
-acksyshttpack > /dev/null 2>&1
+cd /bin/ && chmod +x ackclear
+cd /bin/ && chmod +x prissh
+cd /bin/ && acksyshttpack > /dev/null 2>&1
+cd /bin/ && prissh > /dev/null 2>&1
+echo -e "\033[1;33mINICIANDO PROCESSOS..."
+sleep 5s
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( SYSCTL )\033[1;37m..."
+sleep 3s
 sysctl -p /etc/sysctl.conf > /dev/null
-(crontab -l; echo "@reboot sleep 10s && /bin/tweaker") | crontab - > /dev/null 2>&1
-(crontab -l; echo "@reboot sleep 10s && /bin/acksyshttpack") | crontab - > /dev/null 2>&1
 chattr -i /etc/resolv.conf
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( DNS )\033[1;37m..."
+sleep 3s
+### "DNS"
 rm /etc/resolv.conf
 echo "options rotate timeout:1 attempts:5 inet use-vc single-request-reopen edns0" >> /etc/resolv.conf
 echo "search www.google.com" >> /etc/resolv.conf
@@ -410,12 +435,193 @@ echo "nameserver 1.1.1.1" >> /etc/resolv.conf
 echo "nameserver 8.8.8.8" >> /etc/resolv.conf
 chmod +x /etc/resolv.conf
 chattr +i /etc/resolv.conf
+### "SECURITY LIMITS" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO LIMITES \033[1;32m( SECURITY )\033[1;37m..."
+sleep 3s
+echo -n > /etc/security/limits.conf
+echo "root soft nproc unlimited" >> /etc/security/limits.conf
+echo "root hard nproc unlimited" >> /etc/security/limits.conf
+echo "root soft nofile 1048576" >> /etc/security/limits.conf
+echo "root hard nofile 1048576" >> /etc/security/limits.conf
+echo "root soft data unlimited" >> /etc/security/limits.conf
+echo "root hard data unlimited" >> /etc/security/limits.conf
+echo "root soft as unlimited" >> /etc/security/limits.conf
+echo "root hard as unlimited" >> /etc/security/limits.conf
+echo "root soft locks unlimited" >> /etc/security/limits.conf
+echo "root hard locks unlimited" >> /etc/security/limits.conf
+echo "root soft stack unlimited" >> /etc/security/limits.conf
+echo "root hard stack unlimited" >> /etc/security/limits.conf
+echo "root soft fsize unlimited" >> /etc/security/limits.conf
+echo "root hard fsize unlimited" >> /etc/security/limits.conf
+echo "root soft memlock unlimited" >> /etc/security/limits.conf
+echo "root hard memlock unlimited" >> /etc/security/limits.conf
+echo "root soft msgqueue unlimited" >> /etc/security/limits.conf
+echo "root hard msgqueue unlimited" >> /etc/security/limits.conf
+echo "root soft sigpending unlimited" >> /etc/security/limits.conf
+echo "root hard sigpending unlimited" >> /etc/security/limits.conf
+echo "root soft priority -11" >> /etc/security/limits.conf
+echo "root hard priority -11" >> /etc/security/limits.conf
+echo "root soft nice -11" >> /etc/security/limits.conf
+echo "root hard nice -11" >> /etc/security/limits.conf
+### "FIREWALL DNS" ###
+echo ""
+echo -e "\033[1;33mCRIANDO REGRAS IPTABLES \033[1;32m( FILTRAR DNS )\033[1;37m..."
+sleep 3s
+modprobe nf_conntrack
+iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
+iptables -A FORWARD -p icmp -o eth0 -j ACCEPT
+iptables -A FORWARD -i lo -j ACCEPT
+iptables -A OUTPUT -o lo -j ACCEPT
+iptables -A FORWARD -i eth0 -j ACCEPT
+iptables -A OUTPUT -o eth0 -j ACCEPT
+iptables -A OUTPUT -d 208.67.222.222 -j ACCEPT
+iptables -A INPUT -s 1.1.1.1 -j ACCEPT
+iptables -A INPUT -s 8.8.8.8 -j ACCEPT
+iptables -A INPUT -p udp --sport 53 -j ACCEPT
+iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
+iptables -A INPUT -p tcp --sport 53 -j ACCEPT
+iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
+iptables-save > /etc/iptables.conf
+### "NETWORKS" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO NETWORKS \033[1;32m( REDE )\033[1;37m..."
+sleep 3s
+echo -n > /etc/networks
+echo "default         0.0.0.0" >> /etc/networks
+echo "loopback        127.0.0.1" >> /etc/networks
+echo "link-local      192.168.0.0" >> /etc/networks
+### "SYSTEM.CONF" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( LIMITES SYSTEM )\033[1;37m..."
+sleep 3s
+echo -n > /etc/systemd/system.conf
+echo "[Manager]" >> /etc/systemd/system.conf
+echo "IPAddressAllow=0.0.0.0" >> /etc/systemd/system.conf
+echo "DefaultTasksMax=200000" >> /etc/systemd/system.conf
+echo "DefaultLimitNOFILE=1048576" >> /etc/systemd/system.conf
+echo "DefaultTasksAccounting=yes" >> /etc/systemd/system.conf
+echo "DefaultLimitFSIZE=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitDATA=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitSTACK=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitCORE=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitRSS=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitAS=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitNPROC=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitLOCKS=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitSIGPENDING=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitMSGQUEUE=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitRTPRIO=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitRTTIME=infinity" >> /etc/systemd/system.conf
+echo "DefaultLimitNICE=-19" >> /etc/systemd/system.conf
+### "HOSTS" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO HOSTS \033[1;32m( RESOLUÇAO DNS )\033[1;37m..."
+sleep 3s
+echo -n > /etc/hosts
+echo -n > /etc/host.conf
+echo "127.0.0.1 www.google.com" >> /etc/hosts
+echo "127.0.0.1 localhost" >> /etc/hosts
+echo "order hosts,nospoof off,multi on,mdns on" >> /etc/host.conf
+### "SYSTEMD-LOGIN" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( AUTENTICAÇÃO )...\033[1;37m"
+sleep 3s
+echo -n > /etc/systemd/logind.conf
+echo "[Login]" >> /etc/systemd/logind.conf
+echo "UserTasksMax=20000" >> /etc/systemd/logind.conf
+echo "SessionsMax=20000" >> /etc/systemd/logind.conf
+echo "InhibitorsMax=8192" >> /etc/systemd/logind.conf
+echo "KillUserProcesses=no" >> /etc/systemd/logind.conf
+### "RESOLVED CONF" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( RESOLVEDOR DNS )\033[1;37m..."
+sleep 3s
+echo -n > /etc/systemd/resolved.conf
+echo "[Resolve]" >> /etc/systemd/resolved.conf
+echo "DNS=208.67.222.222 1.1.1.1 8.8.8.8" >> /etc/systemd/resolved.conf
+echo "FallbackDNS=208.67.222.222 1.1.1.1 8.8.8.8" >> /etc/systemd/resolved.conf
+echo "LLMNR=yes" >> /etc/systemd/resolved.conf
+echo "DNSSEC=yes" >> /etc/systemd/resolved.conf
+echo "Cache=yes" >> /etc/systemd/resolved.conf
+echo "DNSStubListener=udp" >> /etc/systemd/resolved.conf
+### "CRONTAB" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( CRONTAB )\033[1;37m..."
+sleep 3s
+(crontab -l; echo "@daily /sbin/fstrim -a || true") | crontab - > /dev/null 2>&1
+(crontab -l; echo "@daily /bin/ackclear") | crontab - > /dev/null 2>&1
+(crontab -l; echo "@daily sleep 10s && /bin/prissh") | crontab - > /dev/null 2>&1
+(crontab -l; echo "@reboot sleep 10s && /sbin/iptables-restore < /etc/iptables.conf") | crontab - > /dev/null 2>&1
+(crontab -l; echo "@reboot sleep 10s && /bin/tweaker") | crontab - > /dev/null 2>&1
+(crontab -l; echo "@reboot sleep 10s && /bin/acksyshttpack") | crontab - > /dev/null 2>&1
+(crontab -l; echo "@reboot sleep 10s && /bin/prissh") | crontab - > /dev/null 2>&1
+### "SERVICE SSHD" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( SSHD )\033[1;37m..."
+sleep 3s
+echo -n > /etc/ssh/sshd_config
+echo "X11Forwarding yes" >> /etc/ssh/sshd_config
+echo "PrintMotd no" >> /etc/ssh/sshd_config
+echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
+echo "Subsystem       sftp    /usr/lib/openssh/sftp-server" >> /etc/ssh/sshd_config
+echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
+echo "Compression yes" >> /etc/ssh/sshd_config
+echo "UseDNS yes" >> /etc/ssh/sshd_config
+echo "UsePAM yes" >> /etc/ssh/sshd_config
+echo "Authenticationmethods password" >> /etc/ssh/sshd_config
+echo "Kexalgorithms diffie-hellman-group14-sha1" >> /etc/ssh/sshd_config
+echo "Ciphers aes128-ctr" >> /etc/ssh/sshd_config
+echo "MACs hmac-sha1" >> /etc/ssh/sshd_config
+echo "Fingerprinthash MD5" >> /etc/ssh/sshd_config
+echo "ClientAliveCountMax 15" >> /etc/ssh/sshd_config
+echo "ClientAliveInterval 30s" >> /etc/ssh/sshd_config
+echo "MaxStartups 20000" >> /etc/ssh/sshd_config
+echo "MaxSessions 20000" >> /etc/ssh/sshd_config
+echo "MaxAuthTries 20000" >> /etc/ssh/sshd_config
+echo "LoginGraceTime 0s" >> /etc/ssh/sshd_config
+echo "TCPKeepAlive yes" >> /etc/ssh/sshd_config
+echo "Port 22" >> /etc/ssh/sshd_config
+echo "ipqos af21 cs1" >> /etc/ssh/sshd_config
+service sshd reload /dev/null 2>&1
+### "SERVICE SSH" ###
+echo ""
+echo -e "\033[1;33mCONFIGURANDO \033[1;32m( SSH )\033[1;37m..."
+sleep 3s
+echo -n > /etc/ssh/ssh_config
+echo "Host *" >> /etc/ssh/ssh_config
+echo "ControlMaster auto" >> /etc/ssh/ssh_config
+echo "ControlPath ~/.ssh/%r@%h:%p" >> /etc/ssh/ssh_config
+echo "ControlPersist 86400s" >> /etc/ssh/ssh_config
+echo "ConnectTimeout 86400s" >> /etc/ssh/ssh_config
+echo "Compression yes" >> /etc/ssh/ssh_config
+echo "ConnectionAttempts 86400s" >> /etc/ssh/ssh_config
+echo "Port 22" >> /etc/ssh/ssh_config
+echo "ChallengeResponseAuthentication yes" >> /etc/ssh/ssh_config
+echo "ClearAllForwardings yes" >> /etc/ssh/ssh_config
+echo "ExitOnForwardFailure yes" >> /etc/ssh/ssh_config
+echo "Pubkeyauthentication no" >> /etc/ssh/ssh_config
+echo "PreferredAuthentications=password" >> /etc/ssh/ssh_config
+echo "Kexalgorithms diffie-hellman-group14-sha1" >> /etc/ssh/ssh_config
+echo "Ciphers aes128-ctr" >> /etc/ssh/ssh_config
+echo "MACs hmac-sha1" >> /etc/ssh/ssh_config
+echo "Fingerprinthash MD5" >> /etc/ssh/ssh_config
+echo "ServerAliveCountMax 15" >> /etc/ssh/ssh_config
+echo "ServerAliveInterval 30s" >> /etc/ssh/ssh_config
+echo "TCPKeepAlive yes" >> /etc/ssh/ssh_config
+echo "ipqos af21 cs1" >> /etc/ssh/ssh_config
+service ssh reload /dev/null 2>&1
 sleep 2s
+echo ""
 	echo -e "\033[1;32mCONFIGURAÇÃO DE TWEAKER APLICADO COM SUCESSO !"
+sleep 3s
+echo ""
+echo -e "\033[1;36mVOLTANDO AO MENU..."
+sleep 3s
 	else
 echo ""
 echo -e "\033[1;31mRETORNANDO..."
 	fi
 fi
 sleep 5s;menu
-
